OPTIONS (ERRORS=50)
LOAD DATA 
INFILE 'D:\DB\DATA_TABLE\BOOK.ldr' "str '{EOL}'"
APPEND
CONTINUEIF NEXT(1:1) = '#'
INTO TABLE "BOOK"
FIELDS TERMINATED BY'|'
OPTIONALLY ENCLOSED BY '"' AND '"'
TRAILING NULLCOLS ( 
"BNUM" CHAR (20),
"BNAME" CHAR (200),
"BAUT" CHAR (200),
"BPUB" CHAR (200),
"BYEAR" CHAR (20),
"BCAT" CHAR (20),
"BDIV" CHAR (20),
"BNOB" CHAR (20),
"BNOBOB" CHAR (20),
"BDCOUNT" CHAR (20),
L_0 FILLER char,
"BDIMG" LOBFILE( L_0) TERMINATED BY EOF NULLIF L_0 = 'null')
