OPTIONS (ERRORS=50)
LOAD DATA 
INFILE 'D:\DB\DATA_TABLE\CUSTOMER.ldr' "str '{EOL}'"
APPEND
CONTINUEIF NEXT(1:1) = '#'
INTO TABLE "CUSTOMER"
FIELDS TERMINATED BY'|'
OPTIONALLY ENCLOSED BY '"' AND '"'
TRAILING NULLCOLS ( 
"CNUM" CHAR (20),
"CPW" CHAR (20),
"CNAME" CHAR (20),
"CAGE" CHAR (20),
"CGEN" CHAR (20),
"CTEL" CHAR (20),
"CLAST" CHAR (20),
"CTYPE" CHAR (20),
"PNUM" CHAR (20),
"TNUM" CHAR (20),
"CSCHOOL" CHAR (50),
"CINT" CHAR (20),
"LNUM" CHAR (20))
