OPTIONS (ERRORS=50)
LOAD DATA 
INFILE 'D:\DB\DATA_TABLE\DAECHUL.ldr' "str '{EOL}'"
APPEND
CONTINUEIF NEXT(1:1) = '#'
INTO TABLE "DAECHUL"
FIELDS TERMINATED BY'|'
OPTIONALLY ENCLOSED BY '"' AND '"'
TRAILING NULLCOLS ( 
"DNUM" CHAR (20),
"CNUM" CHAR (20),
"BNUM" CHAR (20),
"DDATE" CHAR (20),
"DRETURN" CHAR (20),
"DRETURNED" CHAR (20))
