OPTIONS (ERRORS=50)
LOAD DATA 
INFILE 'D:\DB\DATA_TABLE\LECTURE.ldr' "str '{EOL}'"
APPEND
CONTINUEIF NEXT(1:1) = '#'
INTO TABLE "LECTURE"
FIELDS TERMINATED BY'|'
OPTIONALLY ENCLOSED BY '"' AND '"'
TRAILING NULLCOLS ( 
"LNUM" CHAR (20),
"LNAME" CHAR (200),
"LLOC" CHAR (50),
"LTAR" CHAR (50),
"LPER" CHAR (200),
"LTIME" CHAR (200),
"LDAY" CHAR (50),
"LTNUM" CHAR (20))
