OPTIONS (ERRORS=50)
LOAD DATA 
INFILE 'D:\DB\DATA_TABLE\LECTUREIMG.ldr' "str '{EOL}'"
APPEND
CONTINUEIF NEXT(1:1) = '#'
INTO TABLE "LECTUREIMG"
FIELDS TERMINATED BY'|'
OPTIONALLY ENCLOSED BY '"' AND '"'
TRAILING NULLCOLS ( 
"FILENAME" CHAR (100),
L_0 FILLER char,
"IMGDATA" LOBFILE( L_0) TERMINATED BY EOF NULLIF L_0 = 'null')
