OPTIONS (ERRORS=50)
LOAD DATA 
INFILE 'D:\DB\DATA_TABLE\RECOMMENDEDBOOKS.ldr' "str '{EOL}'"
APPEND
CONTINUEIF NEXT(1:1) = '#'
INTO TABLE "RECOMMENDEDBOOKS"
FIELDS TERMINATED BY'|'
OPTIONALLY ENCLOSED BY '"' AND '"'
TRAILING NULLCOLS ( 
"TNUM" CHAR (20),
"BNUM" CHAR (20))
