--------------------------------------------------------
--  DDL for Table BOOK
--------------------------------------------------------

  CREATE TABLE "BOOK" 
   (	"BNUM" VARCHAR2(20 BYTE), 
	"BNAME" VARCHAR2(200 BYTE), 
	"BAUT" VARCHAR2(200 BYTE), 
	"BPUB" VARCHAR2(200 BYTE), 
	"BYEAR" VARCHAR2(20 BYTE), 
	"BCAT" VARCHAR2(20 BYTE), 
	"BDIV" VARCHAR2(20 BYTE), 
	"BNOB" VARCHAR2(20 BYTE), 
	"BNOBOB" VARCHAR2(20 BYTE), 
	"BDCOUNT" VARCHAR2(20 BYTE), 
	"BDIMG" BLOB
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" 
 LOB ("BDIMG") STORE AS SECUREFILE (
  TABLESPACE "USERS" ENABLE STORAGE IN ROW CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES 
  STORAGE(INITIAL 106496 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;

   COMMENT ON COLUMN "BOOK"."BNUM" IS '도서번호';
   COMMENT ON COLUMN "BOOK"."BNAME" IS '도서명';
   COMMENT ON COLUMN "BOOK"."BAUT" IS '저자';
   COMMENT ON COLUMN "BOOK"."BPUB" IS '출판사';
   COMMENT ON COLUMN "BOOK"."BYEAR" IS '출판연도';
   COMMENT ON COLUMN "BOOK"."BCAT" IS '카테고리';
   COMMENT ON COLUMN "BOOK"."BDIV" IS '구분';
   COMMENT ON COLUMN "BOOK"."BNOB" IS '장서량';
   COMMENT ON COLUMN "BOOK"."BNOBOB" IS '대여중인장서량';
   COMMENT ON COLUMN "BOOK"."BDCOUNT" IS '대출횟수';
   COMMENT ON COLUMN "BOOK"."BDIMG" IS '표지이미지';
   COMMENT ON TABLE "BOOK"  IS '도서정보';
