--------------------------------------------------------
--  DDL for Table CUSTOMER
--------------------------------------------------------

  CREATE TABLE "CUSTOMER" 
   (	"CNUM" VARCHAR2(20 BYTE), 
	"CPW" VARCHAR2(20 BYTE), 
	"CNAME" VARCHAR2(20 BYTE), 
	"CAGE" VARCHAR2(20 BYTE), 
	"CGEN" VARCHAR2(20 BYTE), 
	"CTEL" VARCHAR2(20 BYTE), 
	"CLAST" VARCHAR2(20 BYTE), 
	"CTYPE" VARCHAR2(20 BYTE), 
	"PNUM" VARCHAR2(20 BYTE), 
	"TNUM" VARCHAR2(20 BYTE), 
	"CSCHOOL" VARCHAR2(50 BYTE), 
	"CINT" VARCHAR2(20 BYTE), 
	"LNUM" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

   COMMENT ON COLUMN "CUSTOMER"."CNUM" IS '회원번호';
   COMMENT ON COLUMN "CUSTOMER"."CPW" IS '회원비번';
   COMMENT ON COLUMN "CUSTOMER"."CNAME" IS '회원이름';
   COMMENT ON COLUMN "CUSTOMER"."CAGE" IS '회원나이';
   COMMENT ON COLUMN "CUSTOMER"."CGEN" IS '회원성별';
   COMMENT ON COLUMN "CUSTOMER"."CTEL" IS '회원연락처';
   COMMENT ON COLUMN "CUSTOMER"."CLAST" IS '마지막접속일';
   COMMENT ON COLUMN "CUSTOMER"."CTYPE" IS '회원타입';
   COMMENT ON COLUMN "CUSTOMER"."PNUM" IS '부모번호';
   COMMENT ON COLUMN "CUSTOMER"."TNUM" IS '선생님번호';
   COMMENT ON COLUMN "CUSTOMER"."CSCHOOL" IS '소속';
   COMMENT ON COLUMN "CUSTOMER"."CINT" IS '관심사';
   COMMENT ON COLUMN "CUSTOMER"."LNUM" IS '강좌번호';
   COMMENT ON TABLE "CUSTOMER"  IS '회원정보';
