--------------------------------------------------------
--  DDL for Table DAECHUL
--------------------------------------------------------

  CREATE TABLE "DAECHUL" 
   (	"DNUM" VARCHAR2(20 BYTE), 
	"CNUM" VARCHAR2(20 BYTE), 
	"BNUM" VARCHAR2(20 BYTE), 
	"DDATE" VARCHAR2(20 BYTE), 
	"DRETURN" VARCHAR2(20 BYTE), 
	"DRETURNED" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

   COMMENT ON COLUMN "DAECHUL"."DNUM" IS '대출번호';
   COMMENT ON COLUMN "DAECHUL"."CNUM" IS '회원번호';
   COMMENT ON COLUMN "DAECHUL"."BNUM" IS '도서번호';
   COMMENT ON COLUMN "DAECHUL"."DDATE" IS '대출일';
   COMMENT ON COLUMN "DAECHUL"."DRETURN" IS '반납예정일';
   COMMENT ON COLUMN "DAECHUL"."DRETURNED" IS '반납일';
   COMMENT ON TABLE "DAECHUL"  IS '대출정보';
