--------------------------------------------------------
--  DDL for Table MANAGER
--------------------------------------------------------

  CREATE TABLE "MANAGER" 
   (	"MNUM" VARCHAR2(20 BYTE), 
	"MPW" VARCHAR2(20 BYTE), 
	"MNAME" VARCHAR2(20 BYTE), 
	"MTEL" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

   COMMENT ON COLUMN "MANAGER"."MNUM" IS '관리자번호';
   COMMENT ON COLUMN "MANAGER"."MPW" IS '관리자비번';
   COMMENT ON COLUMN "MANAGER"."MNAME" IS '관리자이름';
   COMMENT ON COLUMN "MANAGER"."MTEL" IS '관리자연락처';
   COMMENT ON TABLE "MANAGER"  IS '관리자정보';
