--------------------------------------------------------
--  Constraints for Table BOOK
--------------------------------------------------------

  ALTER TABLE "BOOK" MODIFY ("BNUM" NOT NULL ENABLE);
  ALTER TABLE "BOOK" MODIFY ("BNAME" NOT NULL ENABLE);
  ALTER TABLE "BOOK" MODIFY ("BAUT" NOT NULL ENABLE);
  ALTER TABLE "BOOK" MODIFY ("BPUB" NOT NULL ENABLE);
  ALTER TABLE "BOOK" MODIFY ("BYEAR" NOT NULL ENABLE);
  ALTER TABLE "BOOK" MODIFY ("BCAT" NOT NULL ENABLE);
  ALTER TABLE "BOOK" MODIFY ("BNOB" NOT NULL ENABLE);
  ALTER TABLE "BOOK" MODIFY ("BNOBOB" NOT NULL ENABLE);
  ALTER TABLE "BOOK" MODIFY ("BDCOUNT" NOT NULL ENABLE);
  ALTER TABLE "BOOK" ADD PRIMARY KEY ("BNUM")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
