--------------------------------------------------------
--  Constraints for Table CUSTOMER
--------------------------------------------------------

  ALTER TABLE "CUSTOMER" MODIFY ("CNUM" NOT NULL ENABLE);
  ALTER TABLE "CUSTOMER" MODIFY ("CPW" NOT NULL ENABLE);
  ALTER TABLE "CUSTOMER" MODIFY ("CNAME" NOT NULL ENABLE);
  ALTER TABLE "CUSTOMER" MODIFY ("CAGE" NOT NULL ENABLE);
  ALTER TABLE "CUSTOMER" MODIFY ("CGEN" NOT NULL ENABLE);
  ALTER TABLE "CUSTOMER" MODIFY ("CTEL" NOT NULL ENABLE);
  ALTER TABLE "CUSTOMER" MODIFY ("CLAST" NOT NULL ENABLE);
  ALTER TABLE "CUSTOMER" MODIFY ("CTYPE" NOT NULL ENABLE);
  ALTER TABLE "CUSTOMER" ADD PRIMARY KEY ("CNUM")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
