--------------------------------------------------------
--  Ref Constraints for Table RECOMMENDEDBOOKS
--------------------------------------------------------

  ALTER TABLE "RECOMMENDEDBOOKS" ADD CONSTRAINT "FK_RECOMMENDEDBOOKS_BNUM_BOOK_BNUM" FOREIGN KEY ("BNUM")
	  REFERENCES "BOOK" ("BNUM") ENABLE;
  ALTER TABLE "RECOMMENDEDBOOKS" ADD CONSTRAINT "FK_RECOMMENDEDBOOKS_TNUM_CUSTOMER_CNUM" FOREIGN KEY ("TNUM")
	  REFERENCES "CUSTOMER" ("CNUM") ENABLE;
